# if you don't have the genomes, you can download them from the correct URL
target_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/002/163/495/GCA_002163495.1_Omyk_1.0/GCA_002163495.1_Omyk_1.0_genomic.fna.gz
query_url:  https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/002/872/995/GCA_002872995.1_Otsh_v1.0/GCA_002872995.1_Otsh_v1.0_genomic.fna.gz



# location of the genome (fasta) of the species you want
# to have the ancestral genome for.  
target_fasta: resources/genomes/target/target.fna

# here is what you can use if you already have it downloaded
#target_fasta: /Users/eriq/Documents/UnsyncedData/omyV6-genome/omyV6Chr.fasta

# location of the genome (fasta) of the closely related species
# that you want to use as the ancestral states
query_fasta: resources/genomes/query/query.fna

# here is what you can use if you already have it downloaded
#query_fasta: /Users/eriq/Documents/UnsyncedData/Otsh_v1.0/Otsh_v1.0_genomic.fna





# path (relative to the top level of the workflow repo) to a file that
# has the names of the chromosomes from the target fasta that you want
# to use.  One name on each line.
target_chroms: config/target_chroms.txt


# path to a file holding the names of the sequences in the query fasta that
# we want to map against the target
query_chroms: config/query_chroms.txt


# SET THIS TO "NULL" if you don't have it yet. (You typically
# make it from the results of the first mapping.)
homolog_sets_csv: config/homolog_sets.csv